on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@722adc6
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@081536e
        with:
          java-version: '8.0.x'
      - uses: actions/cache@cffae95
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Download Eclipse
        run: |
          wget 'https://www.eclipse.org/downloads/download.php?file=/eclipse/downloads/drops4/R-4.6.3-201703010400/eclipse-SDK-4.6.3-linux-gtk-x86_64.tar.gz&r=1' -O eclipse-SDK-4.6.3-linux-gtk-x86_64.tar.gz
          tar xzvf eclipse-SDK-4.6.3-linux-gtk-x86_64.tar.gz eclipse
          echo "eclipseRoot.dir=$(pwd)/eclipse" > eclipsePlugin/local.properties
      - name: Build
        run: |
          ./gradlew spotlessCheck build smoketest sonarqube --no-daemon
        env:
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
