on:
  push:
    branches:
      - master
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@722adc6
      - name: Set up JDK 8
        uses: actions/setup-java@081536e
        with:
          java-version: '8.0.x'
      - uses: actions/cache@cffae95
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Download Eclipse
        run: |
          wget 'https://www.eclipse.org/downloads/download.php?file=/eclipse/downloads/drops4/R-4.6.3-201703010400/eclipse-SDK-4.6.3-linux-gtk-x86_64.tar.gz&r=1' -O eclipse-SDK-4.6.3-linux-gtk-x86_64.tar.gz
          tar xzvf eclipse-SDK-4.6.3-linux-gtk-x86_64.tar.gz eclipse
          echo "eclipseRoot.dir=$(pwd)/eclipse" > eclipsePlugin/local.properties
      - name: Build
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$GPG_SECRET_PASSPHRASE" --output .github/workflows/secring .github/workflows/secring.gpg
          gpg --quiet --batch --yes --decrypt --passphrase="$GPG_SECRET_PASSPHRASE" --output spotbugs.jks .github/workflows/spotbugs.jks.gpg
          gpg --import --batch .github/workflows/secring
          export GPG_TTY=$(tty)
          echo ossrhUsername=eller86 >> gradle.properties
          echo "ossrhPassword=${SONATYPE_PASSWORD}" >> gradle.properties
          echo "signing.gnupg.keyName=${SIGNING_KEY_ID}" >> gradle.properties
          echo "signing.gnupg.passphrase=${SIGNING_PASSWORD}" >> gradle.properties
          echo "signing.gnupg.executable=gpg" >> gradle.properties
          echo "keystorepass=${KEYSTORE_PASS}" >> gradle.properties
          ./gradlew publish --no-daemon
        env:
          GPG_SECRET_PASSPHRASE: ${{ secrets.GPG_SECRET_PASSPHRASE }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
